version: '3.8'

services:
  # 1. Backend Application Service
  app:
    build: .
    container_name: gridspark_app
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=db
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - db
    networks:
      - app-network

  # 2. Database Service
  db:
    image: mysql:8.0
    container_name: gridspark_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # 3. Nginx Reverse Proxy Service
  nginx:
    image: nginx:latest
    container_name: gridspark_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      # The volume for '/dist' has been removed as it's no longer needed
    depends_on:
      - app
    networks:
      - app-network

  # 4. Certbot Service for SSL
  certbot:
    image: certbot/certbot
    container_name: gridspark_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
