version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: gridspark_db
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: node_app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: admin1234
      DATABASE_NAME: gridspark_db
    depends_on:
      - db
  # Nginx Reverse Proxy Service
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Map host port 80 to container port 80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  mysql_data:
